# Generated by Django 5.2.7 on 2025-10-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64, verbose_name='customer name')),
                ('customer_email', models.EmailField(max_length=64, verbose_name='email')),
                ('vat_id', models.CharField(max_length=11, verbose_name='vat id')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('zipcode', models.CharField(max_length=8, verbose_name='zipcode')),
                ('street', models.CharField(max_length=128, verbose_name='street')),
                ('street_number', models.CharField(max_length=8, verbose_name='street number')),
                ('complement', models.CharField(blank=True, max_length=128, verbose_name='complement')),
                ('district', models.CharField(max_length=32, verbose_name='district')),
                ('city', models.CharField(max_length=32, verbose_name='city')),
                ('region', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='region')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
